import numpy as np
array = np.arange(1,11)
a = array - 2 
b = np.multiply(array,10)
c = np.sqrt(array)
d = np.mod(array,2)
e = np.power(array,3)
f = np.cos(array)
g = np.sin(array) 
h = np.tan(array)
i = np.log(array)
print("original array: ")
print(array)
print("all the elements of array is divide by 2 normally or not using ufunc (universal function) : ")
print(a)
print("all the elements of array  are numltiply by 10 using ufunc or universal function :")
print(b)
print("square root of all the elements of array using ufunc or universal function :")
print(c)
print("finding reminder of the all the elements of the array if divided by 2 using unfunc: ")
print(d)
print("all the elements of the array are power of 3 using ufunc or universal function :")
print(e)
print("cos0 value of all the elements of the array using ufunc or universal function :")
print(f)
print("sin0 value of all the elements of the array using ufunc or universal function :")
print(g)
print("tan0 value of all the elements of the array using ufunc or universal function :")
print(h)
print("logarithmic value of all the elements of the array using ufunc or universal function :")
print(i)
