import numpy as np
array = np.arange(1,11)
a = np.sum(array)
b = np.mean(array)
c = np.median(array)
d = np.std(array)  
e = np.var(array)
f = np.min(array)
g = np.max(array)
print("original array: ")
print(array)
print("sum of all elements of array: ")
print(a)
print("mean of the array: ")
print(b)
print("median of the array: ")
print(c)
print("standard deivation of the array: ")
print(d)
print("variance of the array: ")
print(e)
print("minimum of the array: ")
print(f)
print("maximum of the array: ")
print(g)